name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMWUzNGE4OTAtYWVjNy00NDQ4LThjMmQtMjY0Njk1OGZkZDJiIiwidGVuYW50X2lkIjoiNmJmZWZmZjFhNTI2NDQ2NmRhMTE3MjVmYTc2YTU5NmQ4ZGY0YTUxOGE2YTU2MjU5ZGI1OTcxNjgxYzU3ZmVlYiIsImludGVybmFsX3NlY3JldCI6Ijc1M2E5ZDcwLTM3MjEtNDY0MS04Y2Q5LWU4NTExNTFhZDFjNiJ9.QZsJG9_lfgCRBUCpsjZJqAq46oqdyezXRIMrEc7zv5o"
JWT_SECRET = "ankit"