name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTIwOGQxZDYtODA5ZC00YzIzLWJhNjUtZmFjZGQ2MzQzZDJiIiwidGVuYW50X2lkIjoiMjY3MDRjYzgxMTI5MTMyMTFhMTAxNjYyY2Y5NTZlZTJiOTEwOWJmZGQxZTRmZmQzNDYyMDZjNGUxYmNkNzg0ZiIsImludGVybmFsX3NlY3JldCI6ImFjYTcxNjFjLTkzOGMtNGJhYy1iMzcxLTc4ODU5MzQ3OTNmOCJ9.l939GMvOafESCCGuw7lIKEjAAthWBZG7lTUY4WCR4cQ"
JWT_SECRET = "ankit"